version: "3.9"

services:
  redis:
    container_name: redis-server
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./resource/config/redis.conf:/usr/local/etc/redis/redis.conf
