version: "3.9"

networks:
  tasks-network:
    name: tasks-network

services:
  redis:
    container_name: redis-server
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./resource/config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - tasks-network
  tasks:
    build: .
    container_name: tasks-server
    command: node dist/main.js
    image: tasks:latest
    ports:
      - 8400:8200
    env_file:
      - .docker.env
    networks:
      - tasks-network
    depends_on:
      - redis
