version: "3"

services:
  redis:
    hostname: redis_tasks_server
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./resource/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/redis/:/data
    networks:
      - net
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 512M
  tasks:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile
    hostname: tasks_server
    ports:
      - 8202:8202
    networks:
      - net
    depends_on:
      - redis
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 512M

networks:
  net: